version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/src-tauri/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
