name: ✨ Feature request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature description
      description: A short summary of the feature or enhancement
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful or important?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative approaches you've thought about
    validations:
      required: false
