name: main

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--arch arm64'
          - platform: 'macos-latest'
            args: '--arch x64'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
          - platform: 'windows-latest'
            args: ''
          - platform: 'windows-11-arm'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install frontend dependencies
        run: npm ci

      - name: run code linting
        run: npm run lint

      - name: mark version in npm
        if: github.event_name == 'release'
        run: npm version --no-git-tag-version ${{ github.ref_name }}

      - name: build application
        run: npm run make -- ${{ matrix.args }}

      - name: Upload Linux ARM64 Assets
        if: github.event_name == 'release' && matrix.platform == 'ubuntu-22.04-arm'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/deb/arm64/easy-web-dashboard_${{ github.ref_name }}_arm64.deb
            ./out/make/rpm/arm64/easy-web-dashboard-${{ github.ref_name }}-1.arm64.rpm

      - name: Upload Linux x64 Assets
        if: github.event_name == 'release' && matrix.platform == 'ubuntu-22.04'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/deb/x64/easy-web-dashboard_${{ github.ref_name }}_x64.deb
            ./out/make/rpm/x64/easy-web-dashboard-${{ github.ref_name }}-1.x64.rpm

      - name: Upload macOS ARM64 Assets
        if: github.event_name == 'release' && matrix.platform == 'macos-latest' && contains(matrix.args, 'arm64')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/easy-web-dashboard-${{ github.ref_name }}-arm64.dmg

      - name: Upload macOS x64 Assets
        if: github.event_name == 'release' && matrix.platform == 'macos-latest' && contains(matrix.args, 'x64')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/easy-web-dashboard-${{ github.ref_name }}-x64.dmg

      - name: Upload Windows x64 Assets
        if: github.event_name == 'release' && matrix.platform == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/squirrel.windows/x64/easy-web-dashboard-${{ github.ref_name }} Setup.exe
          name: easy-web-dashboard-${{ github.ref_name }}-x64-setup.exe

      - name: Upload Windows ARM64 Assets
        if: github.event_name == 'release' && matrix.platform == 'windows-11-arm'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/make/squirrel.windows/arm64/easy-web-dashboard-${{ github.ref_name }} Setup.exe
          name: easy-web-dashboard-${{ github.ref_name }}-arm64-setup.exe
